"""add_search_vector_and_feedback

Revision ID: 6df0bd4d1be7
Revises: e57b346b345d
Create Date: 2026-03-14 21:24:57.374336

"""
from typing import Sequence, Union
import uuid
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df0bd4d1be7'
down_revision: Union[str, None] = 'e57b346b345d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add Feedback table (dropping existing phantom table if it exists)
    op.execute("DROP TABLE IF EXISTS feedback CASCADE")
    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_type", sa.String(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["intel_items.id"]),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # 2. Add search_vector column and index via raw SQL (GENERATED columns aren't autogenerated)
    op.execute("""
        ALTER TABLE intel_items
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (
            to_tsvector('english', coalesce(title, '') || ' ' || coalesce(excerpt, '') || ' ' || coalesce(summary, ''))
        ) STORED
    """)
    op.execute("""
        CREATE INDEX intel_items_search_idx ON intel_items USING gin(search_vector)
    """)


def downgrade() -> None:
    # 1. Drop index and column
    op.execute("DROP INDEX IF EXISTS intel_items_search_idx")
    op.execute("ALTER TABLE intel_items DROP COLUMN IF EXISTS search_vector")

    # 2. Drop Feedback table
    op.drop_table("feedback")
